# Generated by Django 3.2.7 on 2021-10-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_attedance_attendance_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='temperature',
            field=models.FloatField(default=0),
        ),
    ]
