# Generated by Django 3.2.8 on 2021-10-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_attendance_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='rollno',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
    ]
