# Generated by Django 3.2.8 on 2021-10-23 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_attendance_rollno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='rollno',
        ),
    ]
